name       : haskell-vty
version    : '5.21'
release    : 3
source     :
    - https://hackage.haskell.org/package/vty-5.21/vty-5.21.tar.gz : 5a79b8b5f3a2ead0db01cfbc34e145cfa8ff36315f0bb075e6d364ae0a937a5b
license    : BSD-3-Clause
component  : programming.haskell
summary    : vty is terminal GUI library in the niche of ncurses.
description: |
    vty is terminal GUI library in the niche of ncurses. It is intended to be easy to use, have no confusing corner cases, and good support for common terminal types.
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-data-default
    - haskell-hashable
    - haskell-microlens-th
    - haskell-microlens-mtl
    - haskell-parallel
    - haskell-parsec
    - haskell-stm
    - haskell-utf8-string
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
