name       : haskell-vty
version    : '5.14'
release    : 2
source     :
    - https://hackage.haskell.org/package/vty-5.14/vty-5.14.tar.gz : 6f96be6c79c55850f09589b940bfebcc774adddf8a8258af2235320893c53912
license    : BSD-3-Clause
component  : programming.haskell
summary    : vty is terminal GUI library in the niche of ncurses.
description: |
    vty is terminal GUI library in the niche of ncurses. It is intended to be easy to use, have no confusing corner cases, and good support for common terminal types.
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-data-default
    - haskell-microlens-th
    - haskell-microlens-mtl
    - haskell-parallel
    - haskell-utf8-string
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
