name       : haskell-vty
version    : 5.15
release    : 1
source     :
    - https://hackage.haskell.org/package/vty-5.15/vty-5.15.tar.gz : 03bf0fa5132c271248e0f721ad9fb3f5003dc93cff99776fcc7cb7920a85d7f7
license    : BSD-3-Clause
component  : programming.haskell
summary    : vty is terminal GUI library in the niche of ncurses.
description: |
    vty is terminal GUI library in the niche of ncurses. It is intended to be easy to use, have no confusing corner cases, and good support for common terminal types.
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-microlens-th
    - haskell-microlens-mtl
    - haskell-parallel
    - haskell-utf8-string
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
