name       : haskell-vty
version    : 5.28.2
release    : 5
source     :
    - https://hackage.haskell.org/package/vty-5.28.2/vty-5.28.2.tar.gz : 3bdf60e9445d0add86cd2c5d398107a2b9cc9e6e24b513c9b7b75d0e9182d149
license    : BSD-3-Clause
component  : programming.haskell
summary    : vty is terminal GUI library in the niche of ncurses.
description: |
    vty is terminal GUI library in the niche of ncurses. It is intended to be easy to use, have no confusing corner cases, and good support for common terminal types.
builddeps  :
    - haskell-ansi-terminal-devel
    - haskell-blaze-builder-devel
    - haskell-cabal-install
    - haskell-hashable-devel
    - haskell-microlens-th-devel
    - haskell-microlens-mtl-devel
    - haskell-parallel-devel
    - haskell-utf8-string-devel
    - haskell-vector-devel
rundeps    :
    - devel :
        - haskell-ansi-terminal-devel
        - haskell-blaze-builder-devel
        - haskell-hashable-devel
        - haskell-microlens-th-devel
        - haskell-microlens-mtl-devel
        - haskell-parallel-devel
        - haskell-utf8-string-devel
        - haskell-vector-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
